# Generated by Django 4.0.4 on 2022-05-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_fotot_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='fotot_receita',
            new_name='foto_receita',
        ),
    ]
